### PR TITLE
Update powersrg.sh

### PR DESCRIPTION
**Pull request by AugWin**
updated for 14.1

### CODE REVIEW

**Comment by Mikej81** [comment]
Does this work on 13.1 also, or just 14.1?

**Comment by Mikej81** [comment]
Going to merge, but make sure you regression test.

**Comment by AugWin** [comment]
Tested on a local 13.1.1.5 VE.  The script worked, but this setting doesn't exist in 13.1 so it threw the error "Syntax Error: "gtm" unexpected argument":
gtm global-settings general { iquery-minimum-tls-version }

**Comment by Mikej81** [comment]
that should be fine.

**Pull request merged**
